# Generated by Django 4.0.6 on 2023-05-31 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0007_alter_niveauscolaire_nom'),
        ('inscription_frais', '0002_remove_fraisscolarite_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquette.classe')),
            ],
        ),
    ]
