# Generated by Django 4.0.6 on 2023-06-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0009_classe_frais_inscription_classe_frais_scolarite'),
        ('inscription_frais', '0003_fraisinscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frais_inscription', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquette.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquette.etudiant')),
            ],
        ),
        migrations.RemoveField(
            model_name='fraisscolarite',
            name='classe',
        ),
        migrations.DeleteModel(
            name='FraisInscription',
        ),
        migrations.DeleteModel(
            name='FraisScolarite',
        ),
    ]
