# Generated by Django 4.0.6 on 2022-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_inter', models.CharField(max_length=50)),
                ('prenoms_inter', models.CharField(max_length=150)),
                ('nom_utilisateur', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=15)),
            ],
        ),
    ]
