# Generated by Django 4.0.6 on 2023-06-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0009_classe_frais_inscription_classe_frais_scolarite'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenant',
            name='classes',
            field=models.ManyToManyField(to='maquette.classe'),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='matieres',
            field=models.ManyToManyField(to='maquette.matiere'),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='intervenant',
            name='taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
