# Generated by Django 4.0.6 on 2023-06-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_intervenant_classes_intervenant_matieres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenant',
            name='statut',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('vacataire', 'Vacataire')], max_length=20, null=True),
        ),
    ]
