# Generated by Django 4.0.6 on 2023-06-18 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_intervenant_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenant',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='matieres',
        ),
    ]
