# Generated by Django 3.1.7 on 2022-07-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20220722_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervenant',
            old_name='Type',
            new_name='type',
        ),
    ]
