# Generated by Django 3.1.7 on 2022-07-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20220722_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Type_user',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='type',
        ),
        migrations.AddField(
            model_name='intervenant',
            name='type_user',
            field=models.ManyToManyField(to='authentication.Type_user'),
        ),
    ]
