# Generated by Django 4.0.6 on 2023-04-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0002_remove_etudiant_pays_remove_etudiant_sexe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='filiere',
        ),
    ]
