# Generated by Django 4.0.6 on 2023-04-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0003_remove_etudiant_cycle_remove_etudiant_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='AnneeAcademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquette.anneeacademique'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='AnneeAcademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquette.anneeacademique'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='AnneeAcademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquette.anneeacademique'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='AnneeAcademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquette.anneeacademique'),
        ),
    ]
