# Generated by Django 4.0.6 on 2023-05-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0005_matiere_coefficient_unitenseignement_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='frais_inscription',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='frais_scolarite',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
