# Generated by Django 4.0.6 on 2023-05-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0006_classe_frais_inscription_classe_frais_scolarite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveauscolaire',
            name='nom',
            field=models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('SUPERIEUR', 'Enseignement supérieur')], max_length=100),
        ),
    ]
