# Generated by Django 4.0.6 on 2023-06-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0007_alter_niveauscolaire_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='frais_inscription',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='frais_scolarite',
        ),
    ]
