# Generated by Django 4.0.6 on 2023-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0008_remove_classe_frais_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='frais_inscription',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='classe',
            name='frais_scolarite',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
