# Generated by Django 4.0.6 on 2023-06-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0009_classe_frais_inscription_classe_frais_scolarite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(max_length=150),
        ),
    ]
