# Generated by Django 4.0.6 on 2023-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0010_alter_classe_nom_alter_cycle_nom_alter_filiere_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='Numero_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='site_web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
