# Generated by Django 4.0.6 on 2023-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0011_etablissement_numero_telephone_etablissement_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='niveau_classe',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
