# Generated by Django 4.0.6 on 2023-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0012_classe_niveau_classe_etudiant_matricule_matiere_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='niveau_classe',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
