# Generated by Django 4.0.6 on 2023-06-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0013_alter_classe_niveau_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='volume_horaire',
            field=models.IntegerField(null=True),
        ),
    ]
