# Generated by Django 4.0.6 on 2023-06-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0014_matiere_volume_horaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='AnneeAcademique',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='classe',
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquette.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquette.classe')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='maquette.etudiant')),
            ],
        ),
    ]
