# Generated by Django 4.0.6 on 2023-06-20 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maquette', '0015_remove_etudiant_anneeacademique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquette.etudiant'),
        ),
    ]
